### ISSUE TITLE
slides: Haiku not in supported platforms

### ISSUE THREAD

**Issue by pulkomandy** [makapuf/bitbox-prez#1]
You could add Haiku to the list of supported development platforms in the slides. There seem to be no sources for the PDF so I can't fix this myself?

**Comment by makapuf** [comment]
Ah sure, my bad ! I don't have the sources here : I'll add it asap

**Comment by makapuf** [comment]
ok well in fact the presentation was on google doc, so the only file there
is is that PDF -which can almost serve as a source by opening it with
LibreOffice (apart from a few gradient backgrounds). should make next ones
with s5.
 closed in be0f79695d900efd86e58903ec6f3aed7c48c448
Thanks Adrien for this (and your work on haiku. donate to the project ! I
did :) (well, not _you_, Adrien))
